title: OpenShift Migration Advisor 문서 한국어 번역
description: OpenShift Migration Advisor documentation Korean translation
url: "https://yesol1108.github.io"
baseurl: "/openshift-migration-advisor-docs-ko"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
defaults:
  - scope:
      path: ""
    values:
      layout: default
